version : '3'

services:
    magento2:
        environment:
        - PHP_SENDMAIL_PATH=/usr/sbin/sendmail -S mailhog:1025
    mailhog:
        image: mailhog/mailhog:v1.0.1
        ports: 
            - 8025:8025
        networks:
            - backend
