name: Docker Image CI

on:
  release:
    types: [published]
  pull_request:
    paths:
      - '**'
      - '!docs/**'
      - '!**/*.md'
    branches:
      - master
jobs:
  build-php:
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
        kind: [fpm-alpine, cli-alpine]
        include:
        # Note that this is not parallelizable, there are dependencies 
        # between these images and the orders they're specified in matters.
        # The order can be determined by looking at the associated Dockerfiles.
        - kind: fpm-alpine
          extrasImages: "fpm-alpine-develop fpm-alpine-develop-xdebug fpm-alpine-dolphin"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }} image
      run: docker build ./php/${{ matrix.php }}/${{ matrix.kind }}
          -t graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }}-$GITHUB_SHA
          -t graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }}

    - name: Build the graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }} dependent images
      run: for image in ${{ matrix.extrasImages }}; do docker build ./php/${{ matrix.php }}/$image
          -t graycore/magento-php:${{ matrix.php }}-$image-$GITHUB_SHA
          -t graycore/magento-php:${{ matrix.php }}-$image

    - name: Login to registry
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      if: ${{ github.event_name == 'release' }}
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    
    - name: Publish latest graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }}
      if: ${{ github.event_name == 'release' }}
      run: docker push graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }}

    - name: Publish graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }}-${{ github.ref_name }}
      if: ${{ github.event_name == 'release' }}
      run: docker push graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }}-${{ github.ref_name }}

    - name: Publish latest graycore/magento-php:${{ matrix.php }} dependent images
      if: ${{ github.event_name == 'release' }}
      run: for image in ${{ matrix.extrasImages }}; do docker push graycore/magento-php:${{ matrix.php }}-$image; done;

    - name: Publish graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }}-${{ github.ref_name }} dependent images
      if: ${{ github.event_name == 'release' }}
      run: for image in ${{ matrix.extrasImages }}; docker push graycore/magento-php:${{ matrix.php }}-$image-${{ github.ref_name }}; done;
  build-nginx:
    strategy:
      matrix:
        nginx: [1.18, 1.19]
        kind: [alpine, alpine-develop]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }} image
        run: docker build ./nginx/${{ matrix.nginx }}/${{ matrix.kind }}
          -t graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }}-${GITHUB_REF##*/}
          -t graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }}

      - name: Login to registry
        if: ${{ github.event_name == 'release' }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      
      - name: Publish graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }} image
        if: ${{ github.event_name == 'release' }}
        run: docker push graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }}

      - name: Publish graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }}-${GITHUB_REF##*/} image
        if: ${{ github.event_name == 'release' }}
        run: docker push graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }}-${GITHUB_REF##*/}
