name: Docker Image CI

on:
  release:
    types: [published]
  pull_request:
    branches:
      - master
jobs:
  build-php:
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the graycore/magento-php:${{ matrix.php }}-fpm-alpine image
      run: docker build ./php/${{ matrix.php }}/alpine
          -t graycore/magento-php:${{ matrix.php }}-fpm-alpine-${GITHUB_REF##*/}
          -t graycore/magento-php:${{ matrix.php }}-fpm-alpine
    
    - name: Build the graycore/magento-php:${{ matrix.php }}-fpm-alpine-develop image
      run: docker build ./php/${{ matrix.php }}/alpine-develop
        -t graycore/magento-php:${{ matrix.php }}-fpm-alpine-develop-${GITHUB_REF##*/}
        -t graycore/magento-php:${{ matrix.php }}-fpm-alpine-develop
    
    - name: Login to registry
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      if: ${{ github.event_name == 'release' }}
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    
    - name: Publish latest graycore/magento-php:${{ matrix.php }}-fpm-alpine image
      if: ${{ github.event_name == 'release' }}
      run: docker push graycore/magento-php:${{ matrix.php }}-fpm-alpine

    - name: Publish tag graycore/magento-php:${{ matrix.php }}-fpm-alpine-${GITHUB_REF##*/} image
      if: ${{ github.event_name == 'release' }}
      run: docker push graycore/magento-php:${{ matrix.php }}-fpm-alpine-${GITHUB_REF##*/}
    
    - name: Publish latest graycore/magento-php:${{ matrix.php }}-fpm-alpine-develop image
      if: ${{ github.event_name == 'release' }} 
      run: docker push graycore/magento-php:${{ matrix.php }}-fpm-alpine-develop

    - name: Publish tag graycore/magento-php:${{ matrix.php }}-fpm-alpine-develop-${GITHUB_REF##*/} image
      if: ${{ github.event_name == 'release' }}
      run: docker push graycore/magento-php:${{ matrix.php }}-fpm-alpine-develop-${GITHUB_REF##*/}
  
  build-nginx:
    strategy:
      matrix:
        nginx: [1.18, 1.19]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the graycore/magento-nginx:${{ matrix.nginx }}-alpine image
        run: docker build ./nginx/${{ matrix.nginx }}/alpine
          -t graycore/magento-nginx:${{ matrix.nginx }}-alpine-${GITHUB_REF##*/}
          -t graycore/magento-nginx:${{ matrix.nginx }}-alpine

      - name: Build the graycore/magento-nginx:${{ matrix.nginx }}-alpine-develop image
        run: docker build ./nginx/${{ matrix.nginx }}/alpine-develop
          -t graycore/magento-nginx:${{ matrix.nginx }}-alpine-develop-${GITHUB_REF##*/}
          -t graycore/magento-nginx:${{ matrix.nginx }}-alpine-develop
      
      - name: Login to registry
        if: ${{ github.event_name == 'release' }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      
      - name: Publish graycore/magento-nginx:${{ matrix.nginx }}-alpine image
        if: ${{ github.event_name == 'release' }}
        run: docker push graycore/magento-nginx:${{ matrix.nginx }}-alpine

      - name: Publish graycore/magento-nginx:${{ matrix.nginx }}-alpine-${GITHUB_REF##*/} image
        if: ${{ github.event_name == 'release' }}
        run: docker push graycore/magento-nginx:${{ matrix.nginx }}-alpine-${GITHUB_REF##*/}

      - name: Publish graycore/magento-nginx:${{ matrix.nginx }}-alpine-develop image
        if: ${{ github.event_name == 'release' }}
        run: docker push graycore/magento-nginx:${{ matrix.nginx }}-alpine-develop
      
      - name: Publish graycore/magento-nginx:${{ matrix.nginx }}-alpine-develop-${GITHUB_REF##*/} image
        if: ${{ github.event_name == 'release' }}
        run: docker push graycore/magento-nginx:${{ matrix.nginx }}-alpine-develop-${GITHUB_REF##*/}
