name: Docker Image CI

on:
  release:
    types: [published]
jobs:
  build-php-7-2-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Alpine PHP image
        run: docker build ./php/7.2/alpine
            -t graycore/magento-php:7.2-fpm-alpine-${GITHUB_REF##*/}
            -t graycore/magento-php:7.2-fpm-alpine
      - name: Login to registry
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - name: Publish latest image
        run: docker push graycore/magento-php:7.2-fpm-alpine
      - name: Publish tag image
        run: docker push graycore/magento-php:7.2-fpm-alpine-${GITHUB_REF##*/}
  build-php-7-2-alpine-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Alpine Develop PHP image
        run: docker build ./php/7.2/alpine-develop
          -t graycore/magento-php:7.2-fpm-alpine-develop-${GITHUB_REF##*/}
          -t graycore/magento-php:7.2-fpm-alpine-develop
      - name: Login to registry
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - name: Publish latest image
        run: docker push graycore/magento-php:7.2-fpm-alpine-develop
      - name: Publish tag image
        run: docker push graycore/magento-php:7.2-fpm-alpine-develop-${GITHUB_REF##*/}
  build-nginx-1-17-alpine-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Alpine Develop Nginx image
        run: docker build ./nginx/1.17/alpine-develop
          -t graycore/magento-nginx:1.17-alpine-develop-${GITHUB_REF##*/}
          -t graycore/magento-nginx:1.17-alpine-develop
      - name: Login to registry
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - name: Publish latest image
        run: docker push graycore/magento-nginx:1.17-alpine-develop
      - name: Publish tag image
        run: docker push graycore/magento-nginx:1.17-alpine-develop-${GITHUB_REF##*/}
