name: Docker Image CI

on:
  release:
    types: [published]
  pull_request:
    paths:
      - '!docs/**'
      - '!**/*.md'
    branches:
      - master
jobs:
  build-php:
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
        kind: [fpm-alpine, fpm-alpine-develop, fpm-alpine-develop-xdebug, fpm-alpine-dolphin, cli-alpine]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }} image
      run: docker build ./php/${{ matrix.php }}/${{ matrix.kind }}
          -t graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }}-${GITHUB_REF##*/}
          -t graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }}
    
    - name: Login to registry
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      if: ${{ github.event_name == 'release' }}
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    
    - name: Publish latest graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }} image
      if: ${{ github.event_name == 'release' }}
      run: docker push graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }}

    - name: Publish tag graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }}-${GITHUB_REF##*/} image
      if: ${{ github.event_name == 'release' }}
      run: docker push graycore/magento-php:${{ matrix.php }}-${{ matrix.kind }}-${GITHUB_REF##*/}
  build-nginx:
    strategy:
      matrix:
        nginx: [1.18, 1.19]
        kind: [alpine, alpine-develop]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }} image
        run: docker build ./nginx/${{ matrix.nginx }}/${{ matrix.kind }}
          -t graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }}-${GITHUB_REF##*/}
          -t graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }}

      - name: Login to registry
        if: ${{ github.event_name == 'release' }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      
      - name: Publish graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }} image
        if: ${{ github.event_name == 'release' }}
        run: docker push graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }}

      - name: Publish graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }}-${GITHUB_REF##*/} image
        if: ${{ github.event_name == 'release' }}
        run: docker push graycore/magento-nginx:${{ matrix.nginx }}-${{ matrix.kind }}-${GITHUB_REF##*/}
